version: '3.9'

services:
  eurekaservice:
    image: eurekaservice:latest
    container_name: eurekaservice
    build:
      context: .
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://configservice:8888
    depends_on:
      - configservice


# Define the custom network
networks:
  app-network:
    driver: bridge # Use the default bridge network driver

