
spring:
  application:
    name: ms-inventario
  datasource:
    url: jdbc:postgresql://localhost:5432/inventariodb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

