server:
  port: 9090
spring:
  application:
    name: ms-productos
  datasource:
    url: jdbc:mysql://localhost:3306/productodb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update




eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
