#spring.application.name=microservice-productos

spring:
  application:
    name: ms-productos
  datasource:
    url: jdbc:mysql://localhost:3306/productodb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
