#spring.application.name=microservice-gateway
server:
  port: 8080


spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventario
          uri: 'http://localhost:8090'
          predicates:
            - Path=/inventario/**
        - id: producto
          uri: 'http://localhost:9090'
          predicates:
            - Path=/producto/**

